# Generated by Django 3.2.4 on 2021-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210713_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='animal_age',
            field=models.CharField(max_length=10, null=True, verbose_name='Yaş'),
        ),
        migrations.AddField(
            model_name='article',
            name='animal_city',
            field=models.CharField(max_length=40, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='article',
            name='animal_gender',
            field=models.CharField(max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='article',
            name='animal_type',
            field=models.CharField(max_length=40, null=True, verbose_name='Tür'),
        ),
    ]
