# Generated by Django 3.2.4 on 2021-07-13 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210713_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('Kedi', 'Kedi'), ('Köpek', 'Köpek'), ('Fare', 'Fare'), ('Kaplumbağa', 'Kaplumbağa'), ('Diğer', 'Diğer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
