# Generated by Django 3.2.4 on 2021-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210713_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='animal_age',
            field=models.CharField(blank=True, choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('Diğer', 'Diğer')], max_length=10, null=True, verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='article',
            name='animal_city',
            field=models.CharField(blank=True, choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Bursa', 'Bursa'), ('Antalya', 'Antalya'), ('Samsun', 'Samsun'), ('Eskişehir', 'Eskişehir'), ('Trabzon', 'Trabzon'), ('Manisa', 'Manisa'), ('Diğer', 'Diğer')], max_length=40, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='article',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('Kedi', 'Kedi'), ('Köpek', 'Köpek'), ('Fare', 'Fare'), ('Kaplumbağa', 'Kaplumbağa'), ('Diğer', 'Diğer')], max_length=30, null=True, verbose_name='Tür'),
        ),
    ]
