# Generated by Django 3.2.4 on 2021-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210713_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='animal_gender',
            field=models.CharField(blank=True, choices=[('erkek', 'erkek'), ('dişi', 'dişi'), ('Diğer', 'Diğer')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
    ]
